name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Git config user
        run: |
          git config user.name CI Build
          git config user.email ci-build+sebastianscatularo@gmail.com
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Verify Change Logs
        run: node common/scripts/install-run-rush.js change --verify
      - name: Rush Install
        run: node common/scripts/install-run-rush.js install
      - name: Rush rebuild
        run: node common/scripts/install-run-rush.js rebuild --verbose
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: wormhole-explorer
          path: apps/explorer/build # or path/to/artifact
  deploy:
    needs: build
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Deploy to GitHub Pages
        with:
          ref: gh-pages
        run: |
          git config user.name CI Build
          git config user.email ci-build+sebastianscatularo@gmail.com

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: wormhole-explorer
        run: |
          git add .
          git commit -m "deploy"
          git -f push
